[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_marketplaace = "DeFFFxVXY4DhBPFTKTphM86W2m1wCPXB9oCAPgP6Rf2E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
